package com.item.eshop.model;

import java.io.Serializable;
import java.util.Date;

public class Comments  implements Serializable {

    private int shopId;

    public void setShoId(int shopId) {
        this.shopId = shopId;
    }
    public int getShopId(){
        return  shopId;
    }
    private String goodName;


    public void setGoodName(String goodName) {
        this.goodName = goodName;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getGoodName() {
        return goodName;
    }
public String getPhone(){
        return phone;
}
    private Date sendtime;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.id
     *
     * @mbg.generated Wed Jul 18 23:33:05 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.good_id
     *
     * @mbg.generated Wed Jul 18 23:33:05 CST 2018
     */
    private Integer goodId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.content
     *
     * @mbg.generated Wed Jul 18 23:33:05 CST 2018
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.user_id
     *
     * @mbg.generated Wed Jul 18 23:33:05 CST 2018
     */
    private String  phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.image
     *
     * @mbg.generated Wed Jul 18 23:33:05 CST 2018
     */
    private String image;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.comments_type
     *
     * @mbg.generated Wed Jul 18 23:33:05 CST 2018
     */
    private Integer status;
    private Good good;

    public Date getSendtime(){
        return sendtime;
    }
    public void setSendtime(Date sendtime){
        this.sendtime=sendtime;
    }
    public Good getGood(){
        return this.good;
    }
    public void setGood(Good good){
    this.good=good;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.id
     *
     * @return the value of comments.id
     *
     * @mbg.generated Wed Jul 18 23:33:05 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.id
     *
     * @param id the value for comments.id
     *
     * @mbg.generated Wed Jul 18 23:33:05 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.good_id
     *
     * @return the value of comments.good_id
     *
     * @mbg.generated Wed Jul 18 23:33:05 CST 2018
     */
    public Integer getGoodId() {
        return goodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.good_id
     *
     * @param goodId the value for comments.good_id
     *
     * @mbg.generated Wed Jul 18 23:33:05 CST 2018
     */
    public void setGoodId(Integer goodId) {
        this.goodId = goodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.content
     *
     * @return the value of comments.content
     *
     * @mbg.generated Wed Jul 18 23:33:05 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.content
     *
     * @param content the value for comments.content
     *
     * @mbg.generated Wed Jul 18 23:33:05 CST 2018
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.user_id
     *
     * @return the value of comments.user_id
     *
     * @mbg.generated Wed Jul 18 23:33:05 CST 2018
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.user_id
     *
     * @param phone the value for comments.user_id
     *
     * @mbg.generated Wed Jul 18 23:33:05 CST 2018
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.image
     *
     * @return the value of comments.image
     *
     * @mbg.generated Wed Jul 18 23:33:05 CST 2018
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.image
     *
     * @param image the value for comments.image
     *
     * @mbg.generated Wed Jul 18 23:33:05 CST 2018
     */
    public void setImage(String image) {
        this.image = image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.comments_type
     *
     * @return the value of comments.comments_type
     *
     * @mbg.generated Wed Jul 18 23:33:05 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.comments_type
     *
     * @param status the value for comments.comments_type
     *
     * @mbg.generated Wed Jul 18 23:33:05 CST 2018
     */
    public void setstatus(Integer status) {
        this.status = status;
    }
}