package com.item.eshop.model;

import java.io.Serializable;
import java.util.Date;

public class point implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point.id
     *
     * @mbg.generated Sun Aug 19 14:10:56 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point.createBy
     *
     * @mbg.generated Sun Aug 19 14:10:56 CST 2018
     */
    private Integer createby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point.updateBy
     *
     * @mbg.generated Sun Aug 19 14:10:56 CST 2018
     */
    private Integer updateby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point.createTime
     *
     * @mbg.generated Sun Aug 19 14:10:56 CST 2018
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point.updateTime
     *
     * @mbg.generated Sun Aug 19 14:10:56 CST 2018
     */
    private Date updatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point.phone
     *
     * @mbg.generated Sun Aug 19 14:10:56 CST 2018
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point.point
     *
     * @mbg.generated Sun Aug 19 14:10:56 CST 2018
     */
    private Integer point;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point.id
     *
     * @return the value of point.id
     *
     * @mbg.generated Sun Aug 19 14:10:56 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point.id
     *
     * @param id the value for point.id
     *
     * @mbg.generated Sun Aug 19 14:10:56 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point.createBy
     *
     * @return the value of point.createBy
     *
     * @mbg.generated Sun Aug 19 14:10:56 CST 2018
     */
    public Integer getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point.createBy
     *
     * @param createby the value for point.createBy
     *
     * @mbg.generated Sun Aug 19 14:10:56 CST 2018
     */
    public void setCreateby(Integer createby) {
        this.createby = createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point.updateBy
     *
     * @return the value of point.updateBy
     *
     * @mbg.generated Sun Aug 19 14:10:56 CST 2018
     */
    public Integer getUpdateby() {
        return updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point.updateBy
     *
     * @param updateby the value for point.updateBy
     *
     * @mbg.generated Sun Aug 19 14:10:56 CST 2018
     */
    public void setUpdateby(Integer updateby) {
        this.updateby = updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point.createTime
     *
     * @return the value of point.createTime
     *
     * @mbg.generated Sun Aug 19 14:10:56 CST 2018
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point.createTime
     *
     * @param createtime the value for point.createTime
     *
     * @mbg.generated Sun Aug 19 14:10:56 CST 2018
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point.updateTime
     *
     * @return the value of point.updateTime
     *
     * @mbg.generated Sun Aug 19 14:10:56 CST 2018
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point.updateTime
     *
     * @param updatetime the value for point.updateTime
     *
     * @mbg.generated Sun Aug 19 14:10:56 CST 2018
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point.phone
     *
     * @return the value of point.phone
     *
     * @mbg.generated Sun Aug 19 14:10:56 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point.phone
     *
     * @param phone the value for point.phone
     *
     * @mbg.generated Sun Aug 19 14:10:56 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point.point
     *
     * @return the value of point.point
     *
     * @mbg.generated Sun Aug 19 14:10:56 CST 2018
     */
    public Integer getPoint() {
        return point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point.point
     *
     * @param point the value for point.point
     *
     * @mbg.generated Sun Aug 19 14:10:56 CST 2018
     */
    public void setPoint(Integer point) {
        this.point = point;
    }
}