package com.item.eshop.mapper;
import com.item.eshop.model.Recomments;
import com.item.eshop.model.Comments;
import org.springframework.stereotype.Repository;
import org.apache.ibatis.annotations.Param;
import java.util.List;
@Repository
public interface CommentsMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbg.generated Wed Jul 18 23:33:05 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbg.generated Wed Jul 18 23:33:05 CST 2018
     */
    int insert(Comments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbg.generated Wed Jul 18 23:33:05 CST 2018
     */
    int insertSelective(Comments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbg.generated Wed Jul 18 23:33:05 CST 2018
     */
    Comments selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbg.generated Wed Jul 18 23:33:05 CST 2018
     */
    int updateByPrimaryKeySelective(Comments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbg.generated Wed Jul 18 23:33:05 CST 2018
     */
    int updateByPrimaryKey(Comments record);
    List<Comments> selectByShopId(int shopid, int page, int num);
     List<Comments> selectAllByShopId(int shopId);
     Comments selectByPrimaryKey(int id);
    List<Comments> selectByGoodId(@Param("shopId") int shopId, @Param("goodName") String goodName, @Param("page") int page, @Param("n") int n, @Param("status") int status);
    List<Recomments> selectByComment(int commentId, int page, int n);
    List<Recomments> selectAllByComment(int commentId);
    List<Comments> selectAllByGoodId(@Param("shopId") int shopId, @Param("goodName") String goodName, @Param("status") int status);
 }