package com.item.eshop.mapper;

import com.item.eshop.model.PointGood;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface PointGoodMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_good
     *
     * @mbg.generated Wed Aug 22 20:06:34 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_good
     *
     * @mbg.generated Wed Aug 22 20:06:34 CST 2018
     */
    int insert(PointGood record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_good
     *
     * @mbg.generated Wed Aug 22 20:06:34 CST 2018
     */
    int insertSelective(PointGood record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_good
     *
     * @mbg.generated Wed Aug 22 20:06:34 CST 2018
     */
    PointGood selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_good
     *
     * @mbg.generated Wed Aug 22 20:06:34 CST 2018
     */
    int updateByPrimaryKeySelective(PointGood record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_good
     *
     * @mbg.generated Wed Aug 22 20:06:34 CST 2018
     */
    int updateByPrimaryKey(PointGood record);

    List<PointGood> selectByQuery(@Param("name") String name, @Param("status") int status);
    List<PointGood> selectByQueryLimit(@Param("name") String name,@Param("status") int status,@Param("page") int page ,@Param("num") int num);


}