package com.item.eshop.mapper;

import com.item.eshop.model.GoodCategory;
import com.item.eshop.model.Province;
import com.item.eshop.model.School;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface ProvinceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table province
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table province
     *
     * @mbggenerated
     */
    int insert(Province record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table province
     *
     * @mbggenerated
     */
    int insertSelective(Province record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table province
     *
     * @mbggenerated
     */
    Province selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table province
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Province record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table province
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Province record);

    /**
     *
     * @return 返回所有省份
     */
    List<Province> selectAllProvince();
    int updateSortUp(int min,int max);

    int updateSortDown(int min,int max);

    int selectCountNum();

    int updateBySort(int newSort,int oldSort);

    int updateById(int sort_no,int id);

    // add: chan  2018/8/9
    List<Province> selectMore();

    List<Province> selectMoreBySort();


}