package com.item.eshop.mapper;

import com.item.eshop.model.Recomments;
import org.springframework.stereotype.Repository;
import java.util.List;
@Repository
public interface RecommentsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recomments
     *
     * @mbg.generated Sun Jul 22 15:06:19 CST 2018
     */
    int insert(Recomments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recomments
     *
     * @mbg.generated Sun Jul 22 15:06:19 CST 2018
     */
    int insertSelective(Recomments record);
    void deleteByPrimaryKey(int id);
    List<Recomments> selectByCommentsId(int commentId);
    List<Recomments> selectByCommentsIdLimit(int commentId, int page, int num);
 }