package com.item.eshop.mapper;

import com.item.eshop.model.GoodCategory;
import com.item.eshop.model.School;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface SchoolMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbggenerated
     */
    int insert(School record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbggenerated
     */
    int insertSelective(School record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbggenerated
     */
    School selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(School record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(School record);

    /**
     * add zheng 2018-6-30
     * @param  学校id
     * @return 返回指定省份内的学校
     */
    List<School> selectByProvinceId(Integer id);

    List<School> selectByName(String id);

    int updateSortUp(int min,int max);

    int updateSortDown(int min,int max);

    int selectCountNum();

    int updateBySort(int newSort,int oldSort);

    int updateById(int sort_no,int id);

    // add: chan  2018/8/9
    List<School> selectMore();

    List<School> selectMoreBySort();

//-----------
    List<School> selectAllSchool();
}