package com.item.eshop.service;

import com.item.eshop.model.School;

import java.util.List;

public interface SchoolService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbggenerated
     */
    int insert(School record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbggenerated
     */
    int insertSelective(School record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbggenerated
     */
    School selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(School record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(School record);

    /**
     * add zheng 2018-6-30
     * @param  学校id
     * @return 返回指定省份内的学校
     */
    List<School> selectByProvinceId(Integer id);

    List<School> selectByName(String id);

    /**
     * add chen 2018-8-9
     * @param  学校id
     * @return update data
     */
    int updateSortUp(int id,int min,int max);

    int updateSortDown(int id,int min,int max);

    int selectCountNum();

    int updateBySort(int newSort,int oldSort);

    int updateById(int sort_no,int id);

    // add: chan  2018/8/9
    List<School> selectMore();
    List<School> selectMoreBySort();
}
